#!/usr/bin/env python
# -*- coding: utf-8 -*-


import rospy
from morai_msgs.msg import CtrlCmd, EgoVehicleStatus
from pidControl import pidControl


class s_driver():
    def __init__(self):
        rospy.init_node('go_drive', anonymous=True)

        cmd_pub=rospy.Publisher('/ctrl_cmd',CtrlCmd, queue_size=1)
        rospy.Subscriber("Ego_topic",EgoVehicleStatus,self.status_callback)
        rate = rospy.Rate(30)

        cmd=CtrlCmd()

        self.pid_controller=pidControl()

        cmd.longlCmdType=1
        # cmd.velocity=20
        cmd.steering=0

        while not rospy.is_shutdown():

 
            cmd_pub.publish(cmd)
            rate.sleep()

    def status_callback(self, data):
        self.current_vel=data.header.velocity

if __name__=='__main__':
    try:
        s_d=s_driver()
    except rospy.ROSInternalException:
        pass